branch-defaults:
  master:
    environment: logopicker-dev
deploy:
  artifact: target/logopicker-0.0.1-SNAPSHOT.zip
global:
  application_name: logopicker
  branch: null
  default_ec2_keyname: henri
  default_platform: Java 8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
