branch-defaults:
  master:
    environment: null
deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: logopicker
  branch: null
  default_ec2_keyname: henri
  default_platform: Docker 17.09.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
